// Generated by CoffeeScript 1.6.3
var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'backbone':
          return _this.Backbone;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var module;
    module = _this.ribcage.collections.baseCollection = factory(_this.require);
    _this.ribcage.collections.BaseCollection = module.Collection;
    return _this.ribcage.collectionMixins.BaseCollection = module.mixin;
  };
}

define(function(require) {
  var Backbone, BaseCollection, baseCollectionMixin;
  Backbone = require('backbone');
  baseCollectionMixin = {};
  BaseCollection = Backbone.Collection.extend(baseCollectionMixin);
  return {
    mixin: baseCollectionMixin,
    Collection: BaseCollection
  };
});
