// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var define;

define = (function(root) {
  var require;
  if (typeof root.define === 'function' && define.amd) {
    return root.define;
  } else {
    require = function(dep) {
      return ((function() {
        (function() {});
        switch (dep) {
          case 'backbone':
            return this.Backbone;
          default:
            return null;
        }
      }).call(this))() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      root.ribcage.collections.baseCollection = module;
      root.ribcage.collections.BaseCollection = module.Collection;
      return root.ribcage.collectionMixins.BaseCollection = module.mixin;
    };
  }
})(this);

define(function(require) {
  var Backbone, BaseCollection, baseCollectionMixin;
  Backbone = require('backbone');
  baseCollectionMixin = {};
  BaseCollection = Backbone.Collection.extend(baseCollectionMixin);
  return {
    mixin: baseCollectionMixin,
    Collection: BaseCollection
  };
});
