// Generated by CoffeeScript 1.6.3
var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'backbone':
          return _this.Backbone;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var collections, mixins, module, _base, _base1;
    collections = (_base = (_this.ribcage || (_this.ribcage = {}))).collections || (_base.collections = {});
    mixins = (_base1 = _this.ribcage).collectionMixins || (_base1.collectionMixins = {});
    module = collections.baseCollection = factory(_this.require);
    collections.BaseCollection = module.Collection;
    return mixins.BaseCollection = module.mixin;
  };
}

define(function(require) {
  var Backbone, BaseCollection, baseCollectionMixin;
  Backbone = require('backbone');
  baseCollectionMixin = {};
  BaseCollection = Backbone.Collections.extend(baseCollectionMixin);
  return {
    mixin: baseCollectionMixin,
    Collection: BaseCollection
  };
});
