// Generated by CoffeeScript 1.6.1
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'jquery':
          return _this.jQuery;
        case 'underscore':
          return _this._;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var _base;
    (_base = (_this.ribcage || (_this.ribcage = {}))).utils || (_base.utils = {});
    return _this.ribcage.utils.serializeForm = factory(_this.require);
  };
}

define(function(require) {
  var $, _;
  $ = require('jquery');
  _ = require('underscore');
  $.serializeObject = function(form) {
    var arr, data, name, value, _i, _len, _ref;
    form = $(form);
    arr = form.serializeArray();
    data = {};
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      _ref = arr[_i], name = _ref.name, value = _ref.value;
      if (name in data) {
        data[name] = _.isArray(data[name]) ? data[name] : [data[name]];
        data[name].push(value);
      } else {
        data[name] = value;
      }
    }
    return data;
  };
  $.fn.serializeObject = function() {
    return $.serializeObject(this);
  };
  return $.serializeObject;
});
