// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'backbone':
          return _this.Backbone;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var mixins, module, views, _base, _base1;
    views = (_base = (_this.ribcage || (_this.ribcage = {}))).views || (_base.views = {});
    mixins = (_base1 = _this.ribcage).viewMixins || (_base1.viewMixins = {});
    module = views.baseView = factory(_this.require);
    views.BaseView = module.View;
    return mixins.BaseView = module.mixin;
  };
}

define(function(require) {
  var Backbone, BaseView, baseViewMixin;
  Backbone = require('backbone');
  baseViewMixin = {};
  BaseView = Backbone.View.extend(baseViewMixin);
  return {
    mixin: baseViewMixin,
    View: BaseView
  };
});
