// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var define;

define = (function(root) {
  var require,
    _this = this;
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    require = function(dep) {
      return (function() {
        switch (dep) {
          case './base':
            return root.ribcage.views.baseView;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      root.ribcage.views.formExtraView = module;
      root.ribcage.views.FormExtraView = module.View;
      return root.ribcage.viewMixins.FormExtraView = module.mixin;
    };
  }
})(this);

define(function(require) {
  var BaseView, FormExtraView, formExtraViewMixin;
  BaseView = require('./base').View;
  formExtraViewMixin = {
    FOCUSABLE_INPUTS: 'input[type=text],input[type=date],input[type=number],input[type=email],textara,select',
    focusFirst: function(form) {
      form = this.$(form);
      return form.find(FOCUSABLE_INPUTS + ':visible:first').focus();
    },
    disableButtons: function(form) {
      form = this.$(form);
      return form.find(':submit').prop('disabled', true);
    },
    enableButtons: function(form) {
      form = this.$(form);
      return form.find(':submit').prop('disabled', false);
    }
  };
  FormExtraView = BaseView.extend(formExtraViewMixin);
  return {
    mixin: formExtraViewMixin,
    View: FormExtraView
  };
});
