// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case './template':
          return _this.ribcage.views.templateView;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var module;
    module = _this.ribcage.views.modelView = factory(_this.require);
    _this.ribcage.views.ModelView = module.View;
    return _this.ribcage.viewMixins.ModelView = module.mixin;
  };
}

define(function(require) {
  var ModelView, modelViewMixin, templateView;
  templateView = require('./template');
  modelViewMixin = {
    getTemplateContext: function() {
      return this.model.toJSON();
    }
  };
  ModelView = templateView.View.extend(modelViewMixin);
  return {
    mixin: modelViewMixin,
    View: ModelView
  };
});
