// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var define;

define = (function(root) {
  var require;
  if (typeof root.define === 'function' && define.amd) {
    return root.define;
  } else {
    require = function(dep) {
      return (function() {
        switch (dep) {
          case './templatebase':
            return root.ribcage.views.templateBaseView;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      ribcage.views.templateView = module;
      ribcage.views.TemplateView = module.View;
      return ribcage.viewMixins.TemplateView = module.mixin;
    };
  }
})(this);

define(function(require) {
  var TemplateBaseView, TemplateView, templateViewMixin;
  TemplateBaseView = require('./templatebase').View;
  templateViewMixin = {
    beforeRender: function() {
      return this;
    },
    afterRender: function(context) {
      return this;
    },
    insertTemplate: function(html) {
      return this.$el.html(html);
    },
    render: function() {
      var context;
      this.beforeRender();
      context = this.getTemplateContext();
      this.insertTemplate(this.renderTemplate(context));
      this.afterRender(context);
      return this;
    }
  };
  TemplateView = TemplateBaseView.extend(templateViewMixin);
  return {
    mixin: templateViewMixin,
    View: TemplateView
  };
});
