// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var define;

define = (function(root) {
  var require;
  if (typeof root.define === 'function' && define.amd) {
    return root.define;
  } else {
    require = function(dep) {
      return (function() {
        switch (dep) {
          case 'underscore':
            return root._;
          case './base':
            return ribcage.views.baseView;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      ribcage.views.templateBaseView = module;
      ribcage.views.TemplateBaseView = module.View;
      return ribcage.viewMixins.TemplateBaseView = module.mixin;
    };
  }
})(this);

define(function(require) {
  var BaseView, TemplateBaseView, templateBaseViewMixin, _;
  _ = require('underscore');
  BaseView = require('./base').View;
  templateBaseViewMixin = {
    templateSettings: null,
    templateSource: '<p>Please override me</p>',
    template: function(data) {
      return _.template(this.templateSource, data, this.templateSettings);
    },
    getTemplateContext: function() {
      return {};
    },
    renderTemplate: function(context) {
      return this.template(context);
    }
  };
  TemplateBaseView = BaseView.extend(templateBaseViewMixin);
  return {
    mixin: templateBaseViewMixin,
    View: TemplateBaseView
  };
});
