// Generated by LiveScript 1.2.0
/**
 * @author Branko Vukelic <branko@brankovukelic.com>
 * @license MIT
 */
var define;
define = function(root){
  if (typeof root.define === 'function' || root.define.amd) {
    return root.define;
  } else {
    return function(factory){
      var ref$;
      return ((ref$ = root.ribcage || (root.ribcage = {})).utils || (ref$.utils = {})).randString = factory();
    };
  }
}(this);
define(function(){
  return {
    rchar: function(charPool){
      charPool == null && (charPool = 'abcdef0123456789');
      return charPool[Math.floor(Math.random() * charPool.length)];
    },
    rstr: function(len, charPool){
      var i;
      len == null && (len = 20);
      charPool == null && (charPool = null);
      return (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = (fn$())).length; i$ < len$; ++i$) {
          i = ref$[i$];
          results$.push(this.rchar(charPool));
        }
        return results$;
        function fn$(){
          var i$, to$, results$ = [];
          for (i$ = 0, to$ = len; i$ < to$; ++i$) {
            results$.push(i$);
          }
          return results$;
        }
      }.call(this)).join('');
    }
  };
});