// Generated by LiveScript 1.2.0
'use strict';
define(function(require){
  var Collection, Backbone, proto;
  Collection = require('ribcage/collections/base').Collection;
  Backbone = require('backbone');
  proto = Collection.prototype;
  return describe('BaseCollection', function(){
    var x$;
    x$ = it;
    x$('should inherit directly from Backbone.Collection', function(){
      var k, ref$, v;
      for (k in ref$ = Backbone.Collection.prototype) {
        v = ref$[k];
        assert.equal(Collection.prototype[k], v);
      }
    });
    x$('should have cleanup', function(){
      assert.typeOf(proto.cleanup, 'function');
    });
  });
});