// Generated by CoffeeScript 1.6.1
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.define = function(factory) {
    var _base;
    (_base = (_this.ribcage || (_this.ribcage = {}))).validators || (_base.validators = {});
    return _this.ribcage.validators.helpers = factory();
  };
}

define(function(require) {
  return {
    notRequired: function(fn) {
      return function(s) {
        if ((s == null) || s === '') {
          return [s, true];
        } else {
          return fn(s);
        }
      };
    },
    mustPass: function(fn) {
      return function(s) {
        s = fn(s);
        return [s, s !== void 0];
      };
    }
  };
});
