// Generated by CoffeeScript 1.6.1
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case './helpers':
          return _this.ribcage.validators.helper;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var _base;
    (_base = (_this.ribcage || (_this.ribcage = {}))).validators || (_base.validators = {});
    return _this.ribcage.validators.methods = factory(_this.require);
  };
}

define(function(require) {
  var mustPass, notRequired, _ref;
  _ref = require('./helpers'), notRequired = _ref.notRequired, mustPass = _ref.mustPass;
  return {
    required: mustPass(function(s) {
      if ((s != null) && s !== '') {
        return s;
      } else {
        return void 0;
      }
    }),
    email: notRequired(mustPass(function(s) {
      if (s.match(/^(?:[\w\!\#\$\%\&\'\*\+\-\/\=\?\^\`\{\|\}\~]+\.)*[\w\!\#\$\%\&\'\*\+\-\/\=\?\^\`\{\|\}\~]+@(?:(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9\-](?!\.)){0,61}[a-zA-Z0-9]?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9\-](?!$)){0,61}[a-zA-Z0-9]?)|(?:\[(?:(?:[01]?\d{1,2}|2[0-4]\d|25[0-5])\.){3}(?:[01]?\d{1,2}|2[0-4]\d|25[0-5])\]))$/)) {
        return s;
      } else {
        return void 0;
      }
    })),
    numeric: notRequired(mustPass(function(s) {
      s = parseFloat(s);
      if (isNaN(s)) {
        return s;
      } else {
        return void 0;
      }
    })),
    integer: notRequired(mustPass(function(s) {
      s = parseInt(s, 10);
      if (isNaN(s)) {
        return s;
      } else {
        return void 0;
      }
    }))
  };
});
