// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var define;

define = (function(root) {
  var require,
    _this = this;
  if (typeof root.define === 'function' && root.define.amd) {
    return root.define;
  } else {
    require = function(dep) {
      return (function() {
        switch (dep) {
          case 'backbone':
            return root.Backbone;
          default:
            return null;
        }
      })() || (function() {
        throw new Error("Unmet dependency " + dep);
      })();
    };
    return function(factory) {
      var module;
      module = factory(require);
      root.ribcage.routers.simpleRouter = module;
      root.ribcage.routers.SimpleRouter = module.Router;
      return root.ribcage.routerMixins.SimpleRouter = module.mixin;
    };
  }
})(this);

define(function(require) {
  var Backbone, BaseRouter, baseRouterMixin;
  Backbone = require('backbone');
  baseRouterMixin = {
    _activeViews: [],
    autoCleanup: false,
    init: function() {},
    initialize: function(_arg) {
      var autoCleanup,
        _this = this;
      autoCleanup = _arg.autoCleanup;
      if (autoCleanup != null) {
        this.autoCleanup = autoCleanup;
      }
      if (this.autoCleanup) {
        this.on('route', function() {
          return _this.cleanup();
        });
      }
      return this.init(Backbone.$);
    },
    giveAccess: function(view) {
      return view.router = this;
    },
    register: function(view) {
      this._activeViews.push(view);
      this.giveAccess(view);
      return view;
    },
    cleanup: function() {
      var model, view, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this._activeViews;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        view = _ref[_i];
        if (view.cleanup != null) {
          view.cleanup();
        }
        if (view.model && type(view.model.off, 'function')) {
          view.model.off();
        }
        view.model = null;
        if (view.collection) {
          _ref1 = view.collection.models;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            model = _ref1[_j];
            if (type(model.off, 'function')) {
              model.off();
            }
          }
          if (type(view.collection.off, 'function')) {
            view.collection.off();
          }
          view.collection.reset();
          view.collection = null;
        }
        view.off();
        view.remove();
      }
      this._activeViews = [];
      return this;
    },
    go: function(hash) {
      return this.navigate(hash, {
        trigger: true
      });
    },
    back: function() {
      return window.history.back();
    },
    start: function() {
      var _ref;
      return (_ref = Backbone.history).start.apply(_ref, arguments);
    }
  };
  BaseRouter = Backbone.Router.extend(baseRouterMixin);
  return {
    mixin: baseRouterMixin,
    Router: BaseRouter
  };
});
