// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'backbone':
          return _this.Backbone;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var mixins, models, module, _base, _base1;
    models = (_base = (_this.ribcage || (_this.ribcage = {}))).models || (_base.models = {});
    mixins = (_base1 = _this.ribcage).modelMixins || (_base1.modelMixins = {});
    module = models.baseModel = factory(_this.require);
    models.BaseModel = module.Model;
    return mixins.BaseModel = module.mixin;
  };
}

define(function(require) {
  var Backbone, BaseModel, baseModelMixin;
  Backbone = require('backbone');
  baseModelMixin = {};
  BaseModel = Backbone.Models.extend(baseModelMixin);
  return {
    mixin: baseModelMixin,
    Model: BaseModel
  };
});
