// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'backbone':
          return _this.Backbone;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    var module;
    module = _this.ribcage.models.baseModel = factory(_this.require);
    _this.ribcage.models.BaseModel = module.Model;
    return _this.ribcage.modelMixins.BaseModel = module.mixin;
  };
}

define(function(require) {
  var Backbone, BaseModel, baseModelMixin;
  Backbone = require('backbone');
  baseModelMixin = {};
  BaseModel = Backbone.Model.extend(baseModelMixin);
  return {
    mixin: baseModelMixin,
    Model: BaseModel
  };
});
